language: node_js
node_js:
  - "8.11.4"

cache: npm

env:
  - ELEMENT_IPFS_MULTIADDR="/ip4/127.0.0.1/tcp/5001" ELEMENT_PROVIDER="http://localhost:8545" ELEMENT_MNEMONIC="weird ensure parent humor crawl doctor machine narrow subway bleak panel worth"

before_install:
  # Install Ethereum Dependencies
  - npm i -g ganache-cli@6.3.0 truffle@5.0.3
  - ganache-cli -m "$MNEMONIC" &>/dev/null &
  - sleep 6 # wait for ganache
  # Check Ganache
  - curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":0}' http://localhost:8545 | jq -r '.'
  - curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6bb093d7bbe83e19ae8173ee29e8830521e1bbb3", "latest"],"id":1}' http://localhost:8545 | jq -r '.'


install:
  - npm i

script:
  - npm run contracts:test
  - npm run contracts:migrate:dev
  - npm run test